# Multi Linear Regression

Multi Linear Regression is similiar like linearRegression. Linear Regression has one dependant and one independant features. MUlti Linear Regression have one dependant feature and more than one independant features.


Simple linear regression model has a continuous outcome and one predictor, whereas a multiple linear regression model has a continuous outcome and multiple predictors (continuous or categorical). 

Mathematical equation of multiple linear regression:

## Steps:-

1.. Python imports

2.. Read and Examine the Data

3.. SPlit the Data if required

4.. Fit the data

5.. PLot the Data

6.. Predict the value

## Python imports

In [66]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
%matplotlib inline

## Read and Examine Data

In [67]:
datasets = pd.read_csv('50_Startups.csv')
backup_datasets = datasets

In [68]:
datasets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
R&D Spend          50 non-null float64
Administration     50 non-null float64
Marketing Spend    50 non-null float64
State              50 non-null object
Profit             50 non-null float64
dtypes: float64(4), object(1)
memory usage: 2.0+ KB


We have 50 values in our datasets. So, it is not required to split the data into test and train data.

In [69]:
# SPlit the independant and dependant variables
datasets.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [70]:
Y = datasets.iloc[:,4:].values

In [71]:
Y[:5]

array([[ 192261.83],
       [ 191792.06],
       [ 191050.39],
       [ 182901.99],
       [ 166187.94]])

In [72]:
X = datasets.iloc[:, :-1].values

In [73]:
X[:5]

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida']], dtype=object)

## ENcoding the Categorical data

In [74]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [75]:
label_encoder = LabelEncoder()
X[:,3] = label_encoder.fit_transform(X[:,3])

In [76]:
X[:5]

array([[165349.2, 136897.8, 471784.1, 2],
       [162597.7, 151377.59, 443898.53, 0],
       [153441.51, 101145.55, 407934.54, 1],
       [144372.41, 118671.85, 383199.62, 2],
       [142107.34, 91391.77, 366168.42, 1]], dtype=object)

In [77]:
# HotEncoder
onehot = OneHotEncoder(categorical_features=[3])

In [78]:
onehot

OneHotEncoder(categorical_features=[3], dtype=<class 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=True)

In [79]:
X = onehot.fit_transform(X).toarray()

In [80]:
X[:5]

array([[  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          1.65349200e+05,   1.36897800e+05,   4.71784100e+05],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.62597700e+05,   1.51377590e+05,   4.43898530e+05],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          1.53441510e+05,   1.01145550e+05,   4.07934540e+05],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          1.44372410e+05,   1.18671850e+05,   3.83199620e+05],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          1.42107340e+05,   9.13917700e+04,   3.66168420e+05]])

Whenever we encode the categorical data using onehotencoding, there is a chances for the dummy variables trap.

In [86]:
# Avoiding the Dummy Variable Trap
X = X[:, 1:]
X[:5]

array([[  1.00000000e+00,   1.65349200e+05,   1.36897800e+05,
          4.71784100e+05],
       [  0.00000000e+00,   1.62597700e+05,   1.51377590e+05,
          4.43898530e+05],
       [  0.00000000e+00,   1.53441510e+05,   1.01145550e+05,
          4.07934540e+05],
       [  1.00000000e+00,   1.44372410e+05,   1.18671850e+05,
          3.83199620e+05],
       [  0.00000000e+00,   1.42107340e+05,   9.13917700e+04,
          3.66168420e+05]])


## Split the data


In [87]:
from sklearn.cross_validation import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(X,Y,test_size=0.2,random_state= 0)


## Fit the model

In [88]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(xtrain,ytrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [89]:
y_pred = regressor.predict(xtest)

In [90]:
y_pred


array([[ 103615.70496732],
       [ 132245.69745432],
       [ 133070.23906339],
       [  72592.46097845],
       [ 179075.96157176],
       [ 116014.3380813 ],
       [  67853.79186105],
       [  98837.47482921],
       [ 114480.26282341],
       [ 168492.58649243]])

## FINISH
